# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: Leg4
  joint_model_group_pose: Walking
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - MultiLeggedRobot
    - hand_to_Leg1_Section1
    - Leg1_Section1_to_Leg1_Section2
    - Leg1_Section2_to_Leg1_Section3
    - hand_to_Leg2_Section1
    - Leg2_Section1_to_Leg2_Section2
    - Leg2_Section2_to_Leg2_Section3
    - hand_to_Leg3_Section1
    - Leg3_Section1_to_Leg3_Section2
    - Leg3_Section2_to_Leg3_Section3
    - hand_to_Leg4_Section1
    - Leg4_Section1_to_Leg4_Section2
    - Leg4_Section2_to_Leg4_Section3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []